/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const InboxLazyImport = createFileRoute('/inbox')()

// Create/Update Routes

const InboxLazyRoute = InboxLazyImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/inbox.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/inbox': typeof InboxLazyRoute
}

export interface FileRoutesByTo {
  '/inbox': typeof InboxLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/inbox': typeof InboxLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/inbox'
  fileRoutesByTo: FileRoutesByTo
  to: '/inbox'
  id: '__root__' | '/inbox'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  InboxLazyRoute: typeof InboxLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  InboxLazyRoute: InboxLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/inbox"
      ]
    },
    "/inbox": {
      "filePath": "inbox.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
